### ISSUE TITLE
Bad error message when showing recipes in ACR

### ISSUE THREAD

**Issue by Gijsreyn** [radius-project/radius#6902] opened 2023-12-02 07:34 UTC
### Steps to reproduce (required)
- Login with ACR login
- Publish by running `rad bicep publish`
- Run the following command

```cli
rad recipe show <recipeName> --resource-type <resourceType>
```

### Observed behavior (required)
```
\"<acrName>.azurecr.io/azure/sql:latest\": HEAD \"https://<acrName>.azurecr.io/v2/azure/<recipeName>/manifests/latest\": GET \"https://<acrName>.azurecr.io/oauth2/token?scope=repository%3Aazure%2F<recipeName>%3Apull\u0026service=<acrName>.azurecr.io\": response status code 401: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information."
```

### Desired behavior (required)
A better error message that explains the problem and tells you how to login to pull. If I were an external customer I wouldn't be sure how to fix this.

[AB#10641](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10641)

**Comment by vinayada1** [comment] 2023-12-04 17:52
Thanks @Gijsreyn for submitting this issue. We will look into this shortly.

**Comment by Gijsreyn** [comment] 2023-12-05 03:55
> Thanks @Gijsreyn for submitting this issue. We will look into this shortly.

Would love to see it. Was trying to setup a demo from an operator perspective, but couldn't go further with the diagnostics Radius is proving.

**Comment by Gijsreyn** [comment] 2023-12-17 07:00
@vinayada1 , may this be related to #6917 ?

**Comment by vishwahiremat** [comment] 2023-12-18 20:11
@Gijsreyn , thats correct. Today we only allow OCI registries with anonymous pull enabled as Bicep registries for Recipes. I wonder if the registry used was configured with private access that causing this issue.

**Comment by Gijsreyn** [comment] 2023-12-19 14:32
> @Gijsreyn , thats correct. Today we only allow OCI registries with anonymous pull enabled as Bicep registries for Recipes. I wonder if the registry used was configured with private access that causing this issue.

I probably think that's the case. I removed my demo, so I have to set it up again. Anyways, thanks for the reply!

**Comment by gpltaylor** [comment] 2023-12-22 18:12
For reference for anyone searching...

# Installing Azure CLI
```
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```
## Login
Login to Azure using the CLI. Note that if you are using Devcontainers then you will need to use the "use-device-code" flag.

```bash
az login 
az login --use-device-code
```

## Login ACR
Next we login to the ACR

```bash
az acr login -n <acr-name>.azurecr.io
```

## Publish our Recipe
Next we publish out Recipe

```bash
rad bicep publish --file <bicep-file> --target "br:<acr-name>.azurecr.io/<image>:<tag>" 
```

**Comment by rynowak** [comment] 2024-01-07 18:07
I'm reopening this because I'm not sure that #6974 addressed it. That PR improves the error message for pushes to a registry (`rad bicep publish`).

**Comment by rynowak** [comment] 2024-01-08 12:56
`rad recipe publish` and `rad recipe show` are different commands. `publish` pushes a Bicep module to an OCI, `show` shows the details of a registry that's been registered.

**Comment by Gijsreyn** [comment] 2024-01-12 11:05
> @Gijsreyn can you confirm. @rynowak this is resolved with the work done under "publish" IMO. The issue talk about "publish" but the command example has "show". I think this was a typo.

Hi,

Just had some time to setup the demo again. This is what I'm trying to do:

az login
az group create --name rg-radius --location westeurope
az aks create --subscription <subscriptionId> --resource-group rg-radius --name aks-rad --node-count 1
az aks get-credentials --subscription <subscriptionId> --resource-group rg-radius --name aks-rad
az group deployment create --resource-group rg-radius --template-file oci.bicep --parameters name=acrradius
az aks update --name aks-rad --resource-group rg-radius --subscription <subscriptionId> --attach-acr acrradius
rad init
rad bicep publish --file sqlfile.bicep --target "br:acrradius.azurecr.io/azure/sql:latest"

In the oci.bicep file:

```bicep
@description('Required. The Azure Container Registry')
param name string

@description('Optional. Provide a location for the registry.')
param location string = resourceGroup().location

@description('Optional. Provide a tier of your Azure Container Registry.')
param sku string = 'Basic'

resource acrResource 'Microsoft.ContainerRegistry/registries@2023-01-01-preview' = {
  name: name
  location: location
  sku: {
    name: sku
  }
  properties: {
    adminUserEnabled: false
  }
}

@description('Output the login server property for later use')
output loginServer string = acrResource.properties.loginServer
```

Still getting authentication required.

**Comment by gpltaylor** [comment] 2024-01-12 17:56
hi @Gijsreyn than you for the detailed response.
Can you please ensure you have logged into the acr. Docker and Az are not joined up at the moment.

`az acr login -n acrradius`

You can then Push to this ACR. Let me know how you get on.
note, the latest version of the CLI will be improved to show better error messaging.

@rynowak this is what I meant in my comment. The issue is with "publish" not "show"

**Comment by Gijsreyn** [comment] 2024-01-13 13:08
@gpltaylor 

Successfully published Bicep file "sqlfile.bicep" to "acrradius.azurecr.io/azure/sql:latest" 

No error message this time.

**Comment by gpltaylor** [comment] 2024-01-13 15:41
Great! Can you please #close this ticket if you're happy everything is working?

**Closed** 2024-01-13 16:17 UTC
Labels: good first issue, triaged, bug
