### ISSUE TITLE
`rad app delete` shows the wrong environment

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#7542] opened 2024-04-24 23:31 UTC
### Steps to reproduce

1. Run `rad group list` to see your groups
2. Run `rad group switch other-group` to change your group
3. Run `rad app list` to see your apps
4. Run `rad env list` to see your environments within that group (Please see the screenshot below)
5. Run `rad app delete my-app` and see that the environment is default and not the app's environment

### Observed behavior

![image](https://github.com/radius-project/radius/assets/5220939/267b60ac-60b1-4740-a9a3-b86613c1bc6a)

![image](https://github.com/radius-project/radius/assets/5220939/06aef74b-0ba0-4ae5-a029-f655a01d5875)
App details

### Desired behavior

`rad app delete app-name` should show the app's environment

### rad Version

RELEASE VERSION BICEP COMMIT
0.32.0 v0.32.0 0.32.0 https://github.com/radius-project/radius/commit/1b8bd4ad7f7a3f9d88b1275b284f7357915a914e

### Operating system

MacOS, Sonoma 14.4.1, Apple Chip

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12058](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12058)

**Comment by sylvainsf** [comment] 2024-04-25 20:01
This is a duplicate of #7541 and should be resolved in the re-design.

**Comment by ytimocin** [comment] 2024-04-25 23:13
This is actually about the CLI showing the wrong environment name for the application to be deleted. I agree, they are kind of related with #7541 but this one could be caused by another part of our code @sylvainsf.

**Comment by sylvainsf** [comment] 2024-04-29 19:39
Will leave open and linked to the other issue.

**Closed** 2024-06-08 20:23 UTC
Labels: triaged, bug
