### ISSUE TITLE
Set prompt width to the user's terminal width

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/radius#5467] opened 2023-04-20 20:18 UTC
Today we hardcode the width of a text prompt:

https://github.com/project-radius/radius/blob/main/pkg/cli/prompt/text/text.go#L38

We should instead have a smart approach where we read the user's terminal window set the prompt width based on that instead.

Today if a user's terminal window is below 20 (40 in the current PR), then the window flashes. Since 40 is still a small width this wouldn't be hit too much

[AB#7647](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7647)

**Comment by willtsai** [comment] 2024-10-23 17:51
potentially a duplicate of #6492, but needs validation

**Closed** 2024-10-30 20:01 UTC
Labels: good first issue, triaged, cli
