### ISSUE TITLE
Validation for Terraform Recipe Template Paths

### ISSUE THREAD

**Issue by kachawla** [radius-project/radius#6642] opened 2023-11-03 16:25 UTC
### Current State/Problem
Currently, we support only [Terraform registry](https://developer.hashicorp.com/terraform/language/modules/sources#terraform-registry) and [HTTP URLs](https://developer.hashicorp.com/terraform/language/modules/sources#http-urls) as allowed module sources for Terraform recipe template paths. However, we lack a proper validation mechanism for when an incorrect source is given during either recipe registration or deployment. Consequently, when a deployment fails, the reason provided to users is ambiguous resulting into a poor user experience.

### Proposed Solution
To address this, we should utilize [Terraform's module parsing logic](https://github.com/hashicorp/terraform-registry-address/blob/main/module.go#L44) to verify the recipe template path when the recipe `templateKind` is provided as Terraform, at recipe registration stage.

## Acceptance criteria
If an unsupported template path for a Terraform recipe is provided, the recipe registration should fail and return a detailed error message to the user.

[AB#10019](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10019)

**Comment by sk593** [comment] 2024-01-11 17:11
Closing, we thought the initial issue was caused by Radius not supporting all module sources. This doesn't seem to be the case as Git, S3, etc are able to be used so there's no need for additional validation.

**Closed by sk593** 2024-01-11 17:11 UTC
Labels: triaged, important, feature
