### ISSUE TITLE
`rad init` gets cutoff when the terminal window is super short

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/radius#6264] opened 2023-09-13 17:21 UTC
### Steps to reproduce (required)

1. Open a terminal window and shorten the height of the terminal window to be ~10 characters:
1. Run `rad init`
1. See that the questions are cut off:

<img width="365" alt="image" src="https://github.com/radius-project/radius/assets/54363786/7c2f97ea-5151-4e05-8e6e-b9c476c324e2">

### Observed behavior (required)

The questions are cut off

### Desired behavior (required)

I would expect the rad CLI to shorten itself so I could see the question.

### Workaround (optional)

Make terminal window longer

### rad Version (required)

0.24

### Operating system (required)

Windows

## Additional context

[AB#9338](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9338)

**Comment by willtsai** [comment] 2024-10-23 17:48
closing as a duplicate of https://github.com/radius-project/radius/issues/6492

**Closed by willtsai** 2024-10-23 17:48 UTC
Labels: triaged, bug
